spring.application.name=smartexpenseapi

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartexpense_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:srg}


# JWT Configuration
smartexpense.app.jwtSecret=${SMARTEXPENSE_JWT_SECRET:smartexpenseSecretKeyForLearningBackendDevelopment2026SmartexpenseSecretKeyForLearningBackendDevelopment2026}
smartexpense.app.jwtExpirationMs=1800000

# ===============================
# JPA / HIBERNATE
# ===============================
# Override with SPRING_JPA_HIBERNATE_DDL_AUTO when a different mode is needed.
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
server.port=${PORT:8081}

# Suppress Spring Security AuthenticationProvider warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
# ===============================
# Admin User Initializer
# ===============================
app.admin.username=${APP_ADMIN_USERNAME}
app.admin.email=${APP_ADMIN_EMAIL}
app.admin.password=${APP_ADMIN_PASSWORD}